const alunos = ['Marcos', 'Daniela', 'João', 'Maria', 'José'];
console.log(alunos);
console.log(alunos[0]);
console.log(alunos[1]);
console.log(alunos[2]);
console.log(alunos[3]);
console.log(alunos[4]);
console.log(alunos[5]);
alunos.push('Antônio');
console.log(alunos[5]);